template: |
  ## What’s changed

  $CHANGES

categories:
  - title: 'Features and enhancements'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'

exclude-labels:
  - 'skip-changelog'
