name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.9'
          - '3.10'
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip

      - name: Build
        run: |
          pip install .
          ./setup.py build sdist bdist

      - name: Install test dependencies
        run: pip install .[test]

      - name: Run tests
        run: pytest -vv --junit-xml=test-results.xml --junit-prefix=py${{ matrix.python-version }}

      - name: Publish test report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the previous step fails
        with:
          check_name: Test report for Python ${{ matrix.python-version }}
          report_paths: test-results.xml
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Setup flake8 annotations
        uses: rbialon/flake8-annotations@v1

      - name: Install lint dependencies
        run: pip install .[lint]

      - name: Lint with flake8
        continue-on-error: true
        run: flake8
